"""
tests/test_win_dhcp_import.py
────────────────────────────────
v5.24.0 (Q20) — jen/services/win_dhcp_import.py: parsing a Windows
`Export-DhcpServer -File x.xml` export and mapping it onto Kea's config
shape. tests/fixtures/windows-dhcp-export.xml (and its
namespace-stripped twin) are synthetic — authored from Microsoft's
documented export shape, not generated by a real DC (see the module's
own docstring and PENDING.md's Q20 entry). Treat this suite as proving
the mapping logic is internally consistent, not as confirmation the
byte-for-byte option encodings match genuine Windows output.
"""

import pathlib

import defusedxml.common
import pytest

from jen.services import win_dhcp_import as w

FIXTURES = pathlib.Path(__file__).resolve().parent / "fixtures"


def _read(name: str) -> bytes:
    return (FIXTURES / name).read_bytes()


# ── duration parsing ─────────────────────────────────────────────────────────


class TestParseDuration:
    def test_days_hours_minutes_seconds(self):
        assert w._parse_duration("8.00:00:00", "x") == (8 * 86400, [])

    def test_hours_minutes_seconds_only(self):
        assert w._parse_duration("12:00:00", "x") == (12 * 3600, [])

    def test_full_form_with_nonzero_hms(self):
        seconds, warnings = w._parse_duration("1.02:03:04", "x")
        assert seconds == 86400 + 2 * 3600 + 3 * 60 + 4
        assert warnings == []

    def test_unlimited_defaults_with_warning(self):
        seconds, warnings = w._parse_duration("Unlimited", "ctx")
        assert seconds == 86400
        assert len(warnings) == 1 and "ctx" in warnings[0]

    def test_absent_defaults_with_warning(self):
        seconds, warnings = w._parse_duration("", "ctx")
        assert seconds == 86400
        assert warnings

    def test_unparsable_defaults_with_warning(self):
        seconds, warnings = w._parse_duration("garbage", "ctx")
        assert seconds == 86400
        assert warnings


# ── RFC 3442 classless-static-route decoding ────────────────────────────────


class TestDecodeClasslessRoutes:
    def test_single_slash_24_route(self):
        # mask=24 (0x18), dest=192.168.10, router=10.0.0.1
        data, warnings = w._decode_classless_routes_hex("18c0a80a0a000001", "x")
        assert data == "192.168.10.0/24 - 10.0.0.1"
        assert warnings == []

    def test_two_routes_concatenated(self):
        route1 = "18c0a80a0a000001"  # 192.168.10.0/24 - 10.0.0.1
        route2 = "080a0a000002"  # mask=8 (0x08), dest=10 (1 octet), router=10.0.0.2
        data, warnings = w._decode_classless_routes_hex(route1 + route2, "x")
        assert data == "192.168.10.0/24 - 10.0.0.1, 10.0.0.0/8 - 10.0.0.2"
        assert warnings == []

    def test_odd_length_hex_drops_last_nibble_with_warning(self):
        data, warnings = w._decode_classless_routes_hex("18c0a80a0a0000012", "x")
        assert warnings
        assert data == "192.168.10.0/24 - 10.0.0.1"

    def test_invalid_mask_length_stops_decoding(self):
        data, warnings = w._decode_classless_routes_hex("ff" + "c0a80a0a000001", "x")
        assert data == ""
        assert warnings

    def test_truncated_entry_stops_decoding(self):
        data, warnings = w._decode_classless_routes_hex("18c0a80a", "x")  # mask+dest, no router
        assert data == ""
        assert warnings

    def test_empty_input(self):
        data, warnings = w._decode_classless_routes_hex("", "x")
        assert data == "" and warnings == []


# ── pool math ────────────────────────────────────────────────────────────────


class TestSplitPoolByExclusions:
    def test_no_exclusions(self):
        assert w.split_pool_by_exclusions("10.0.0.10", "10.0.0.20", []) == [
            (w._ip2int("10.0.0.10"), w._ip2int("10.0.0.20"))
        ]

    def test_exclusion_in_the_middle_splits_into_two(self):
        segs = w.split_pool_by_exclusions("10.0.0.10", "10.0.0.20", [("10.0.0.14", "10.0.0.16")])
        assert segs == [
            (w._ip2int("10.0.0.10"), w._ip2int("10.0.0.13")),
            (w._ip2int("10.0.0.17"), w._ip2int("10.0.0.20")),
        ]

    def test_exclusion_at_the_start(self):
        segs = w.split_pool_by_exclusions("10.0.0.10", "10.0.0.20", [("10.0.0.10", "10.0.0.12")])
        assert segs == [(w._ip2int("10.0.0.13"), w._ip2int("10.0.0.20"))]

    def test_exclusion_at_the_end(self):
        segs = w.split_pool_by_exclusions("10.0.0.10", "10.0.0.20", [("10.0.0.18", "10.0.0.20")])
        assert segs == [(w._ip2int("10.0.0.10"), w._ip2int("10.0.0.17"))]

    def test_exclusion_covering_the_whole_range_yields_no_pools(self):
        segs = w.split_pool_by_exclusions("10.0.0.10", "10.0.0.20", [("10.0.0.1", "10.0.0.254")])
        assert segs == []

    def test_multiple_non_overlapping_exclusions(self):
        segs = w.split_pool_by_exclusions(
            "10.0.0.1", "10.0.0.100", [("10.0.0.10", "10.0.0.19"), ("10.0.0.50", "10.0.0.59")]
        )
        assert segs == [
            (w._ip2int("10.0.0.1"), w._ip2int("10.0.0.9")),
            (w._ip2int("10.0.0.20"), w._ip2int("10.0.0.49")),
            (w._ip2int("10.0.0.60"), w._ip2int("10.0.0.100")),
        ]


class TestCarvePool:
    def test_carves_a_pool_out_of_the_middle(self):
        segs = [(w._ip2int("10.0.0.1"), w._ip2int("10.0.0.100"))]
        new_segs, ok = w._carve_pool(segs, w._ip2int("10.0.0.40"), w._ip2int("10.0.0.50"))
        assert ok is True
        assert (w._ip2int("10.0.0.1"), w._ip2int("10.0.0.39")) in new_segs
        assert (w._ip2int("10.0.0.51"), w._ip2int("10.0.0.100")) in new_segs

    def test_refuses_a_range_spanning_two_segments(self):
        segs = [(w._ip2int("10.0.0.1"), w._ip2int("10.0.0.10")), (w._ip2int("10.0.0.20"), w._ip2int("10.0.0.30"))]
        new_segs, ok = w._carve_pool(segs, w._ip2int("10.0.0.5"), w._ip2int("10.0.0.25"))
        assert ok is False
        assert new_segs == segs

    def test_refuses_a_range_outside_every_segment(self):
        segs = [(w._ip2int("10.0.0.1"), w._ip2int("10.0.0.10"))]
        new_segs, ok = w._carve_pool(segs, w._ip2int("10.0.0.50"), w._ip2int("10.0.0.60"))
        assert ok is False
        assert new_segs == segs


# ── policy -> class conditions ───────────────────────────────────────────────


class TestConditionToRule:
    def test_vendor_class(self):
        rule, warning = w._condition_to_rule({"type": "VendorClass", "value": "Cisco"}, "x")
        assert warning is None
        assert rule == {"field": "vendor_class", "op": "equals", "value": "Cisco"}

    def test_user_class(self):
        rule, _ = w._condition_to_rule({"type": "UserClass", "value": "guest"}, "x")
        assert rule["field"] == "user_class"

    def test_client_id(self):
        rule, _ = w._condition_to_rule({"type": "ClientId", "value": "AABBCC"}, "x")
        assert rule["field"] == "client_id"

    def test_relay_agent_information(self):
        rule, _ = w._condition_to_rule({"type": "RelayAgentInformation", "value": "circuit1"}, "x")
        assert rule["field"] == "circuit_id"

    def test_mac_address_full_no_wildcard(self):
        rule, warning = w._condition_to_rule({"type": "MACAddress", "value": "00-11-22-33-44-55"}, "x")
        assert warning is None
        assert rule == {"field": "mac", "op": "equals", "value": "00-11-22-33-44-55"}

    def test_mac_address_three_byte_wildcard_is_oui(self):
        rule, _ = w._condition_to_rule({"type": "MACAddress", "value": "00-11-22*"}, "x")
        assert rule["field"] == "mac_oui"
        assert rule["value"] == "00-11-22"

    def test_mac_address_wildcard_with_more_than_three_bytes_is_not_oui(self):
        rule, _ = w._condition_to_rule({"type": "MACAddress", "value": "00-11-22-33*"}, "x")
        assert rule["field"] == "mac"

    def test_unsupported_condition_type(self):
        rule, warning = w._condition_to_rule({"type": "Subnet", "value": "x"}, "ctx")
        assert rule is None
        assert warning and "ctx" in warning


class TestPolicyToClass:
    def _policy(self, **kw):
        defaults = {
            "name": "p",
            "enabled": True,
            "processing_order": 1,
            "condition": "AND",
            "conditions": [],
            "ip_ranges": [],
        }
        defaults.update(kw)
        return w.Policy(**defaults)

    def test_simple_equals_policy(self):
        p = self._policy(conditions=[{"type": "VendorClass", "operator": "Equals", "value": "Cisco"}])
        cls, warnings = w.policy_to_class(p, "ctx")
        assert warnings == []
        assert cls == {"name": "p", "test": "option[60].hex == 'Cisco'"}

    def test_or_combinator(self):
        p = self._policy(
            condition="OR",
            conditions=[
                {"type": "VendorClass", "operator": "Equals", "value": "Cisco"},
                {"type": "UserClass", "operator": "Equals", "value": "voip"},
            ],
        )
        cls, _ = w.policy_to_class(p, "ctx")
        assert " or " in cls["test"]

    def test_and_combinator(self):
        p = self._policy(
            condition="AND",
            conditions=[
                {"type": "VendorClass", "operator": "Equals", "value": "Cisco"},
                {"type": "UserClass", "operator": "Equals", "value": "voip"},
            ],
        )
        cls, _ = w.policy_to_class(p, "ctx")
        assert " and " in cls["test"]

    def test_not_equals_single_condition_negates(self):
        p = self._policy(conditions=[{"type": "UserClass", "operator": "NotEquals", "value": "trusted"}])
        cls, warnings = w.policy_to_class(p, "ctx")
        assert warnings == []
        assert cls["test"] == "not (option[77].hex == 'trusted')"

    def test_not_equals_multi_condition_is_refused(self):
        p = self._policy(
            conditions=[
                {"type": "UserClass", "operator": "NotEquals", "value": "trusted"},
                {"type": "VendorClass", "operator": "Equals", "value": "Cisco"},
            ]
        )
        cls, warnings = w.policy_to_class(p, "ctx")
        assert cls is None
        assert any("NotEquals" in msg for msg in warnings)

    def test_mixed_equals_and_notequals_is_refused(self):
        p = self._policy(
            conditions=[
                {"type": "UserClass", "operator": "NotEquals", "value": "trusted"},
                {"type": "VendorClass", "operator": "NotEquals", "value": "Cisco"},
            ]
        )
        # both NotEquals (2 conditions) -> refused by the single-condition rule
        cls, warnings = w.policy_to_class(p, "ctx")
        assert cls is None

    def test_disabled_policy_is_skipped(self):
        p = self._policy(enabled=False, conditions=[{"type": "VendorClass", "value": "Cisco"}])
        cls, warnings = w.policy_to_class(p, "ctx")
        assert cls is None
        assert any("disabled" in msg for msg in warnings)

    def test_no_conditions_is_skipped(self):
        p = self._policy(conditions=[])
        cls, warnings = w.policy_to_class(p, "ctx")
        assert cls is None

    def test_unsupported_condition_skips_whole_policy(self):
        p = self._policy(conditions=[{"type": "Subnet", "value": "x"}])
        cls, warnings = w.policy_to_class(p, "ctx")
        assert cls is None
        assert any("not supported" in msg for msg in warnings)

    def test_name_with_spaces_is_sanitized(self):
        p = self._policy(name="VoIP Phones", conditions=[{"type": "VendorClass", "value": "Cisco"}])
        cls, warnings = w.policy_to_class(p, "ctx")
        assert cls["name"] == "VoIP_Phones"
        assert any("sanitized" in msg for msg in warnings)

    def test_policy_options_become_class_option_data(self):
        p = self._policy(
            conditions=[{"type": "VendorClass", "value": "Cisco"}],
            ip_ranges=[],
        )
        p.options = {66: "tftp.example.com"}
        cls, _ = w.policy_to_class(p, "ctx")
        assert cls["option-data"] == [
            {"name": "tftp-server-name", "code": 66, "space": "dhcp4", "csv-format": True, "data": "tftp.example.com"}
        ]


# ── options mapping ──────────────────────────────────────────────────────────


class TestOptionsToKea:
    def test_known_option_maps_through_the_catalog(self):
        entries, timers, warnings = w._options_to_kea({3: "10.0.0.1"}, "ctx")
        assert warnings == []
        assert timers == {}
        assert entries == [{"name": "routers", "code": 3, "space": "dhcp4", "csv-format": True, "data": "10.0.0.1"}]

    def test_unknown_code_is_skipped_with_a_warning(self):
        entries, _timers, warnings = w._options_to_kea({250: "whatever"}, "ctx")
        assert entries == []
        assert any("250" in msg and "catalog" in msg for msg in warnings)

    def test_249_converts_to_121_with_a_warning(self):
        entries, _timers, warnings = w._options_to_kea({249: "18c0a80a0a000001"}, "ctx")
        assert entries[0]["code"] == 121
        assert entries[0]["data"] == "192.168.10.0/24 - 10.0.0.1"
        assert any("249" in msg for msg in warnings)

    def test_249_ignored_when_121_also_present(self):
        entries, _timers, warnings = w._options_to_kea({121: "18c0a80a0a000001", 249: "ff"}, "ctx")
        assert len(entries) == 1 and entries[0]["code"] == 121
        assert any("249" in msg and "ignored" in msg for msg in warnings)

    def test_invalid_value_is_skipped_with_a_warning(self):
        entries, _timers, warnings = w._options_to_kea({3: "not-an-ip"}, "ctx")
        assert entries == []
        assert warnings

    def test_51_58_59_are_returned_as_timers_not_entries(self):
        """v5.28.0 (Q24, F6) — lease-related codes never reach the
        catalog/option-data path; scope_to_subnet is what merges them
        into the subnet block."""
        entries, timers, warnings = w._options_to_kea({51: "3600", 58: "1800", 59: "3150"}, "ctx")
        assert entries == []
        assert warnings == []
        assert timers == {"valid-lifetime": "3600", "renew-timer": "1800", "rebind-timer": "3150"}

    def test_81_is_dropped_with_one_ddns_line(self):
        entries, timers, warnings = w._options_to_kea({81: "23"}, "ctx")
        assert entries == []
        assert timers == {}
        assert warnings == [w._OPTION_81_WARNING]


# ── reservations ─────────────────────────────────────────────────────────────


class TestParseReservationsViaScope:
    def test_mac_normalization_and_type_dhcp_imported(self):
        data = _read("windows-dhcp-export.xml")
        plan = w.parse_export(data)
        lan = next(s for s in plan.scopes if s.name == "LAN")
        dhcp_res = next(r for r in lan.reservations if r.ip == "10.0.1.5")
        assert dhcp_res.mac == "00:11:22:33:44:55"
        assert dhcp_res.hostname == "printer.lan"

    def test_non_mac_client_id_is_warned_and_skipped(self):
        data = _read("windows-dhcp-export.xml")
        plan = w.parse_export(data)
        lan = next(s for s in plan.scopes if s.name == "LAN")
        assert any("not a MAC" in msg or "not-a-mac-address" in msg for msg in plan.warnings)
        assert "10.0.1.7" not in [r.ip for r in lan.reservations]

    def test_type_both_is_imported(self):
        """v5.28.0 (Q24, F4) — `Both` ("DHCP and BOOTP") is Windows'
        own default and Kea only speaks DHCP, so it's just a plain
        reservation to us; only `Bootp` is skipped."""
        data = _read("windows-dhcp-export.xml")
        plan = w.parse_export(data)
        lan = next(s for s in plan.scopes if s.name == "LAN")
        both_res = next(r for r in lan.reservations if r.ip == "10.0.1.6")
        assert both_res.mac == "aa:bb:cc:dd:ee:ff"


# ── full parser on the fixture(s) ────────────────────────────────────────────


class TestParseExportFixture:
    @pytest.mark.parametrize("filename", ["windows-dhcp-export.xml", "windows-dhcp-export-no-ns.xml"])
    def test_parses_namespaced_and_stripped_copies_identically(self, filename):
        plan = w.parse_export(_read(filename))
        assert [s.name for s in plan.scopes] == ["LAN", "Guest WiFi", "Solo Subnet"]
        assert plan.server_options == {42: "10.0.0.53"}
        assert plan.superscopes == {"HQ": ["10.0.1.0", "10.0.2.0"]}
        assert plan.classes == [{"name": "MSFT 5.0", "type": "Vendor"}]

    def test_inactive_scope_is_flagged(self):
        plan = w.parse_export(_read("windows-dhcp-export.xml"))
        guest = next(s for s in plan.scopes if s.name == "Guest WiFi")
        assert guest.state == "Inactive"
        assert any("Inactive" in msg for msg in plan.warnings)

    def test_billion_laughs_is_refused_not_silently_empty(self):
        with pytest.raises(defusedxml.common.EntitiesForbidden):
            w.parse_export(_read("billion-laughs.xml"))

    def test_superscope_membership_read_from_the_scope_itself(self):
        """v5.28.0 (Q24, F2) — the real export carries membership on
        <SuperScopeName> on each scope, not (only) a top-level
        <Superscopes> list."""
        xml = b"""<?xml version="1.0"?>
        <DHCPServer xmlns="http://schemas.microsoft.com/windows/DHCPServer">
          <IPv4 xmlns="">
            <Scopes>
              <Scope><ScopeId>10.1.1.0</ScopeId><Name>A</Name><SubnetMask>255.255.255.0</SubnetMask>
                <StartRange>10.1.1.10</StartRange><EndRange>10.1.1.100</EndRange>
                <LeaseDuration>1.00:00:00</LeaseDuration><State>Active</State>
                <SuperScopeName>HQ</SuperScopeName></Scope>
              <Scope><ScopeId>10.1.2.0</ScopeId><Name>B</Name><SubnetMask>255.255.255.0</SubnetMask>
                <StartRange>10.1.2.10</StartRange><EndRange>10.1.2.100</EndRange>
                <LeaseDuration>1.00:00:00</LeaseDuration><State>Active</State>
                <SuperScopeName>HQ</SuperScopeName></Scope>
            </Scopes>
          </IPv4>
        </DHCPServer>"""
        plan = w.parse_export(xml)
        assert plan.superscopes == {"HQ": ["10.1.1.0", "10.1.2.0"]}

    def test_broken_scope_is_skipped_not_crashed_on(self):
        """v5.28.0 (Q24, F3) — a scope missing a required field (here
        an empty StartRange) never reaches the pool math; it's dropped
        with a warning instead of raising AddressValueError later."""
        xml = b"""<?xml version="1.0"?>
        <DHCPServer xmlns="http://schemas.microsoft.com/windows/DHCPServer">
          <IPv4 xmlns="">
            <Scopes>
              <Scope><ScopeId>10.2.1.0</ScopeId><Name>Broken</Name><SubnetMask>255.255.255.0</SubnetMask>
                <StartRange></StartRange><EndRange>10.2.1.100</EndRange>
                <LeaseDuration>1.00:00:00</LeaseDuration><State>Active</State></Scope>
            </Scopes>
          </IPv4>
        </DHCPServer>"""
        plan = w.parse_export(xml)
        assert plan.scopes == []
        assert any("missing/invalid StartRange" in msg for msg in plan.warnings)


# ── to_kea, end to end against the fixture ──────────────────────────────────


class TestToKea:
    SUBNET_NAMES = {
        "10.0.1.0": {"id": 10, "name": "LAN"},
        "10.0.2.0": {"id": 11, "name": "Guest WiFi"},
        "10.0.3.0": {"id": 12, "name": "Solo Subnet"},
    }
    ALL_SELECTED = {
        "scopes": {"10.0.1.0": True, "10.0.2.0": True, "10.0.3.0": True},
        "server_options": True,
    }

    def _plan(self):
        return w.parse_export(_read("windows-dhcp-export.xml"))

    def test_default_selection_only_includes_active_scopes(self):
        plan = self._plan()
        cfg, _res, declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, {"scopes": {}})
        assert 11 not in declared  # Guest WiFi is Inactive, not selected by default
        assert 10 in declared and 12 in declared

    def test_server_options_only_imported_when_selected(self):
        plan = self._plan()
        cfg, _res, _declared, _report = w.to_kea(
            plan, None, self.SUBNET_NAMES, {"scopes": {"10.0.3.0": True}, "server_options": False}
        )
        assert "option-data" not in cfg["Dhcp4"] or cfg["Dhcp4"]["option-data"] == []

    def test_superscope_becomes_a_shared_network_when_two_members_included(self):
        plan = self._plan()
        cfg, _res, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, self.ALL_SELECTED)
        nets = cfg["Dhcp4"]["shared-networks"]
        assert len(nets) == 1 and nets[0]["name"] == "HQ"
        ids_in_network = {s["id"] for s in nets[0]["subnet4"]}
        assert ids_in_network == {10, 11}

    def test_lone_superscope_member_does_not_get_a_shared_network(self):
        plan = self._plan()
        selections = {"scopes": {"10.0.1.0": True, "10.0.3.0": True}, "server_options": False}
        cfg, _res, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, selections)
        assert "shared-networks" not in cfg["Dhcp4"] or cfg["Dhcp4"]["shared-networks"] == []
        top_ids = {s["id"] for s in cfg["Dhcp4"].get("subnet4", [])}
        assert 10 in top_ids  # only 1 of HQ's 2 scopes selected -> no shared network

    def test_solo_subnet_is_top_level(self):
        plan = self._plan()
        cfg, _res, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, self.ALL_SELECTED)
        top_ids = {s["id"] for s in cfg["Dhcp4"].get("subnet4", [])}
        assert top_ids == {12}

    def test_reservations_carry_the_right_subnet_id(self):
        plan = self._plan()
        cfg, reservations, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, self.ALL_SELECTED)
        printer = next(r for r in reservations if r["ip-address"] == "10.0.1.5")
        assert printer == {
            "subnet-id": 10,
            "hw-address": "00:11:22:33:44:55",
            "ip-address": "10.0.1.5",
            "hostname": "printer.lan",
        }

    def test_classless_route_121_lands_on_the_lan_subnet(self):
        plan = self._plan()
        cfg, _res, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, self.ALL_SELECTED)
        lan = next(s for net in cfg["Dhcp4"]["shared-networks"] for s in net["subnet4"] if s["id"] == 10)
        codes = {o["code"] for o in lan["option-data"]}
        assert 121 in codes

    def test_policy_with_ip_range_gets_a_dedicated_guarded_pool(self):
        plan = self._plan()
        cfg, _res, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, self.ALL_SELECTED)
        lan = next(s for net in cfg["Dhcp4"]["shared-networks"] for s in net["subnet4"] if s["id"] == 10)
        voip_pool = next(p for p in lan["pools"] if p["pool"] == "10.0.1.200 - 10.0.1.219")
        assert voip_pool.get("client-class") == "VoIP_Phones"

    def test_policy_without_ip_ranges_guards_the_whole_subnet(self):
        plan = self._plan()
        cfg, _res, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, self.ALL_SELECTED)
        lan = next(s for net in cfg["Dhcp4"]["shared-networks"] for s in net["subnet4"] if s["id"] == 10)
        assert lan.get("client-class") == "Guest_Devices"

    def test_disabled_policy_never_becomes_a_class(self):
        plan = self._plan()
        cfg, _res, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, self.ALL_SELECTED)
        names = {c["name"] for c in cfg["Dhcp4"]["client-classes"]}
        assert "Disabled_Legacy_Rule" not in names

    def test_existing_cidr_is_skipped_with_a_warning(self):
        plan = self._plan()
        existing = {"Dhcp4": {"subnet4": [{"id": 99, "subnet": "10.0.3.0/24", "pools": []}]}}
        cfg, _res, declared, report = w.to_kea(plan, existing, self.SUBNET_NAMES, self.ALL_SELECTED)
        assert 12 not in declared
        assert any("already exists" in msg for msg in report)

    def test_does_not_mutate_the_existing_config(self):
        import copy

        plan = self._plan()
        existing = {"Dhcp4": {"subnet4": []}}
        snapshot = copy.deepcopy(existing)
        w.to_kea(plan, existing, self.SUBNET_NAMES, self.ALL_SELECTED)
        assert existing == snapshot

    def test_scope_with_no_chosen_subnet_id_is_skipped(self):
        plan = self._plan()
        names = dict(self.SUBNET_NAMES)
        del names["10.0.3.0"]
        cfg, _res, declared, report = w.to_kea(plan, None, names, self.ALL_SELECTED)
        assert 12 not in declared
        assert any("no subnet id chosen" in msg for msg in report)


# ── the real Export-DhcpServer fixture (v5.28.0, Q24, F8) ───────────────────
#
# tests/fixtures/windows-dhcp-export-real.xml is sanitized from a real
# Windows Server 2019/2022 export (see its own header comment) — every
# number asserted below was computed by actually running the parser
# against it (the scratchpad importlib harness — this file's own
# session-scoped DB fixture blocks a plain `pytest` invocation, see
# CLAUDE.md's "Local verification" section), not inferred from the
# export's contents by reading the XML.


class TestRealExportFixture:
    _NAMES = {"10.10.10.0": {"id": 1, "name": "LAN"}, "10.10.30.0": {"id": 2, "name": "IoT"}}
    _SELECTED = {"scopes": {"10.10.10.0": True, "10.10.30.0": True}, "server_options": True}

    def _plan(self):
        return w.parse_export(_read("windows-dhcp-export-real.xml"))

    def _to_kea(self, plan):
        return w.to_kea(plan, None, self._NAMES, self._SELECTED)

    def test_two_scopes_parsed_with_real_element_shaped_fields(self):
        """The v5.24.0 parser read every field via _attr() and got
        nothing from this file (ChatGPT #11) — F1's _field() reads the
        real format's child-element shape too."""
        plan = self._plan()
        assert len(plan.scopes) == 2
        assert {s.scope_id for s in plan.scopes} == {"10.10.10.0", "10.10.30.0"}

    def test_subnets_have_the_real_cidrs_pools_and_lifetimes(self):
        plan = self._plan()
        cfg, _res, _declared, _report = self._to_kea(plan)
        subnets = {s["id"]: s for s in cfg["Dhcp4"]["subnet4"]}
        assert subnets[1]["subnet"] == "10.10.10.0/23"
        assert subnets[1]["pools"] == [{"pool": "10.10.10.50 - 10.10.10.250"}]
        assert subnets[1]["valid-lifetime"] == 86400
        assert {o["code"] for o in subnets[1]["option-data"]} == {3, 6}  # routers, dns — no domain-name

        assert subnets[2]["subnet"] == "10.10.30.0/24"
        assert subnets[2]["pools"] == [{"pool": "10.10.30.1 - 10.10.30.240"}]
        assert subnets[2]["valid-lifetime"] == 1209600
        assert {o["code"] for o in subnets[2]["option-data"]} == {3, 6, 15}  # + domain-name

    def test_53_reservations_imported_4_non_mac_skipped(self):
        plan = self._plan()
        non_mac = [msg for msg in plan.warnings if "not a MAC" in msg]
        assert len(non_mac) == 4
        _cfg, reservations, _declared, _report = self._to_kea(plan)
        assert len(reservations) == 53

    def test_option_81_dropped_everywhere_with_exactly_one_report_line(self):
        """v5.28.0 (Q24, F6). `plan.server_options` still carries the raw
        parsed value right after parse_export() — the drop happens at
        _options_to_kea()'s MAPPING time, in to_kea() — so this checks
        the real, end-to-end guarantee: nothing from option 81 survives
        into the pushed config, and the many places that see it
        (server/scope/reservation) collapse to one report line."""
        plan = self._plan()
        assert plan.server_options == {81: "23"}
        cfg, _res, _declared, report = self._to_kea(plan)
        assert cfg["Dhcp4"].get("option-data", []) == []
        assert report.count(w._OPTION_81_WARNING) == 1

    def test_reservation_10_10_10_53_carries_its_own_dns_override(self):
        plan = self._plan()
        _cfg, reservations, _declared, _report = self._to_kea(plan)
        row = next(r for r in reservations if r["ip-address"] == "10.10.10.53")
        assert row["option-data"] == [
            {
                "name": "domain-name-servers",
                "code": 6,
                "space": "dhcp4",
                "csv-format": True,
                "data": "10.10.11.199, 10.10.11.201",
            }
        ]

    def test_review_page_mapping_never_raises(self):
        """The real bug this whole step exists to fix: scope_to_subnet
        raised AddressValueError on the empty strings _attr() produced
        from this file, 500ing the review page."""
        plan = self._plan()
        for scope in plan.scopes:
            mapped = w.scope_to_subnet(scope, 1)
            assert mapped.subnet["subnet"]


class TestRealExportHonestyLines:
    """F7 — the unmodified real fixture has MAC filtering disabled
    (Allow=false/Deny=false) and no IPv6 scopes, so neither honesty
    line fires from it as-is; string-edit a copy to exercise each."""

    def test_unmodified_fixture_has_neither_line(self):
        plan = w.parse_export(_read("windows-dhcp-export-real.xml"))
        assert not any("filtering is enabled" in msg for msg in plan.warnings)
        assert not any("IPv6 scopes" in msg for msg in plan.warnings)

    def test_filters_enabled_produces_the_allow_deny_line(self):
        data = _read("windows-dhcp-export-real.xml").replace(b"<Allow>false</Allow>", b"<Allow>true</Allow>", 1)
        plan = w.parse_export(data)
        assert any(
            "MAC allow/deny filtering is enabled in Windows (1 allow / 0 deny entries)" in m for m in plan.warnings
        )

    def test_ipv6_scopes_produce_the_ipv6_line(self):
        data = _read("windows-dhcp-export-real.xml").replace(
            b"<StatelessStore>",
            b"<Scopes><Scope><ScopeId>fd00::</ScopeId></Scope></Scopes><StatelessStore>",
            1,
        )
        plan = w.parse_export(data)
        assert any("IPv6 scopes are not imported (IPv4 only)" in m for m in plan.warnings)
