"""
tests/test_win_dhcp_import.py
────────────────────────────────
v5.24.0 (Q20) — jen/services/win_dhcp_import.py: parsing a Windows
`Export-DhcpServer -File x.xml` export and mapping it onto Kea's config
shape. tests/fixtures/windows-dhcp-export.xml (and its
namespace-stripped twin) are synthetic — authored from Microsoft's
documented export shape, not generated by a real DC (see the module's
own docstring and PENDING.md's Q20 entry). Treat this suite as proving
the mapping logic is internally consistent, not as confirmation the
byte-for-byte option encodings match genuine Windows output.
"""

import pathlib

import defusedxml.common
import pytest

from jen.services import win_dhcp_import as w

FIXTURES = pathlib.Path(__file__).resolve().parent / "fixtures"


def _read(name: str) -> bytes:
    return (FIXTURES / name).read_bytes()


# ── duration parsing ─────────────────────────────────────────────────────────


class TestParseDuration:
    def test_days_hours_minutes_seconds(self):
        assert w._parse_duration("8.00:00:00", "x") == (8 * 86400, [])

    def test_hours_minutes_seconds_only(self):
        assert w._parse_duration("12:00:00", "x") == (12 * 3600, [])

    def test_full_form_with_nonzero_hms(self):
        seconds, warnings = w._parse_duration("1.02:03:04", "x")
        assert seconds == 86400 + 2 * 3600 + 3 * 60 + 4
        assert warnings == []

    def test_unlimited_defaults_with_warning(self):
        seconds, warnings = w._parse_duration("Unlimited", "ctx")
        assert seconds == 86400
        assert len(warnings) == 1 and "ctx" in warnings[0]

    def test_absent_defaults_with_warning(self):
        seconds, warnings = w._parse_duration("", "ctx")
        assert seconds == 86400
        assert warnings

    def test_unparsable_defaults_with_warning(self):
        seconds, warnings = w._parse_duration("garbage", "ctx")
        assert seconds == 86400
        assert warnings


# ── RFC 3442 classless-static-route decoding ────────────────────────────────


class TestDecodeClasslessRoutes:
    def test_single_slash_24_route(self):
        # mask=24 (0x18), dest=192.168.10, router=10.0.0.1
        data, warnings = w._decode_classless_routes_hex("18c0a80a0a000001", "x")
        assert data == "192.168.10.0/24 - 10.0.0.1"
        assert warnings == []

    def test_two_routes_concatenated(self):
        route1 = "18c0a80a0a000001"  # 192.168.10.0/24 - 10.0.0.1
        route2 = "080a0a000002"  # mask=8 (0x08), dest=10 (1 octet), router=10.0.0.2
        data, warnings = w._decode_classless_routes_hex(route1 + route2, "x")
        assert data == "192.168.10.0/24 - 10.0.0.1, 10.0.0.0/8 - 10.0.0.2"
        assert warnings == []

    def test_odd_length_hex_drops_last_nibble_with_warning(self):
        data, warnings = w._decode_classless_routes_hex("18c0a80a0a0000012", "x")
        assert warnings
        assert data == "192.168.10.0/24 - 10.0.0.1"

    def test_invalid_mask_length_stops_decoding(self):
        data, warnings = w._decode_classless_routes_hex("ff" + "c0a80a0a000001", "x")
        assert data == ""
        assert warnings

    def test_truncated_entry_stops_decoding(self):
        data, warnings = w._decode_classless_routes_hex("18c0a80a", "x")  # mask+dest, no router
        assert data == ""
        assert warnings

    def test_empty_input(self):
        data, warnings = w._decode_classless_routes_hex("", "x")
        assert data == "" and warnings == []


# ── pool math ────────────────────────────────────────────────────────────────


class TestSplitPoolByExclusions:
    def test_no_exclusions(self):
        assert w.split_pool_by_exclusions("10.0.0.10", "10.0.0.20", []) == [
            (w._ip2int("10.0.0.10"), w._ip2int("10.0.0.20"))
        ]

    def test_exclusion_in_the_middle_splits_into_two(self):
        segs = w.split_pool_by_exclusions("10.0.0.10", "10.0.0.20", [("10.0.0.14", "10.0.0.16")])
        assert segs == [
            (w._ip2int("10.0.0.10"), w._ip2int("10.0.0.13")),
            (w._ip2int("10.0.0.17"), w._ip2int("10.0.0.20")),
        ]

    def test_exclusion_at_the_start(self):
        segs = w.split_pool_by_exclusions("10.0.0.10", "10.0.0.20", [("10.0.0.10", "10.0.0.12")])
        assert segs == [(w._ip2int("10.0.0.13"), w._ip2int("10.0.0.20"))]

    def test_exclusion_at_the_end(self):
        segs = w.split_pool_by_exclusions("10.0.0.10", "10.0.0.20", [("10.0.0.18", "10.0.0.20")])
        assert segs == [(w._ip2int("10.0.0.10"), w._ip2int("10.0.0.17"))]

    def test_exclusion_covering_the_whole_range_yields_no_pools(self):
        segs = w.split_pool_by_exclusions("10.0.0.10", "10.0.0.20", [("10.0.0.1", "10.0.0.254")])
        assert segs == []

    def test_multiple_non_overlapping_exclusions(self):
        segs = w.split_pool_by_exclusions(
            "10.0.0.1", "10.0.0.100", [("10.0.0.10", "10.0.0.19"), ("10.0.0.50", "10.0.0.59")]
        )
        assert segs == [
            (w._ip2int("10.0.0.1"), w._ip2int("10.0.0.9")),
            (w._ip2int("10.0.0.20"), w._ip2int("10.0.0.49")),
            (w._ip2int("10.0.0.60"), w._ip2int("10.0.0.100")),
        ]


class TestCarvePool:
    def test_carves_a_pool_out_of_the_middle(self):
        segs = [(w._ip2int("10.0.0.1"), w._ip2int("10.0.0.100"))]
        new_segs, ok = w._carve_pool(segs, w._ip2int("10.0.0.40"), w._ip2int("10.0.0.50"))
        assert ok is True
        assert (w._ip2int("10.0.0.1"), w._ip2int("10.0.0.39")) in new_segs
        assert (w._ip2int("10.0.0.51"), w._ip2int("10.0.0.100")) in new_segs

    def test_refuses_a_range_spanning_two_segments(self):
        segs = [(w._ip2int("10.0.0.1"), w._ip2int("10.0.0.10")), (w._ip2int("10.0.0.20"), w._ip2int("10.0.0.30"))]
        new_segs, ok = w._carve_pool(segs, w._ip2int("10.0.0.5"), w._ip2int("10.0.0.25"))
        assert ok is False
        assert new_segs == segs

    def test_refuses_a_range_outside_every_segment(self):
        segs = [(w._ip2int("10.0.0.1"), w._ip2int("10.0.0.10"))]
        new_segs, ok = w._carve_pool(segs, w._ip2int("10.0.0.50"), w._ip2int("10.0.0.60"))
        assert ok is False
        assert new_segs == segs


# ── policy -> class conditions ───────────────────────────────────────────────


class TestConditionToRule:
    def test_vendor_class(self):
        rule, warning = w._condition_to_rule({"type": "VendorClass", "value": "Cisco"}, "x")
        assert warning is None
        assert rule == {"field": "vendor_class", "op": "equals", "value": "Cisco"}

    def test_user_class(self):
        rule, _ = w._condition_to_rule({"type": "UserClass", "value": "guest"}, "x")
        assert rule["field"] == "user_class"

    def test_client_id(self):
        rule, _ = w._condition_to_rule({"type": "ClientId", "value": "AABBCC"}, "x")
        assert rule["field"] == "client_id"

    def test_relay_agent_information(self):
        rule, _ = w._condition_to_rule({"type": "RelayAgentInformation", "value": "circuit1"}, "x")
        assert rule["field"] == "circuit_id"

    def test_mac_address_full_no_wildcard(self):
        rule, warning = w._condition_to_rule({"type": "MACAddress", "value": "00-11-22-33-44-55"}, "x")
        assert warning is None
        assert rule == {"field": "mac", "op": "equals", "value": "00-11-22-33-44-55"}

    def test_mac_address_three_byte_wildcard_is_oui(self):
        rule, _ = w._condition_to_rule({"type": "MACAddress", "value": "00-11-22*"}, "x")
        assert rule["field"] == "mac_oui"
        assert rule["value"] == "00-11-22"

    def test_mac_address_wildcard_with_more_than_three_bytes_is_not_oui(self):
        rule, _ = w._condition_to_rule({"type": "MACAddress", "value": "00-11-22-33*"}, "x")
        assert rule["field"] == "mac"

    def test_unsupported_condition_type(self):
        rule, warning = w._condition_to_rule({"type": "Subnet", "value": "x"}, "ctx")
        assert rule is None
        assert warning and "ctx" in warning


class TestPolicyToClass:
    def _policy(self, **kw):
        defaults = {
            "name": "p",
            "enabled": True,
            "processing_order": 1,
            "condition": "AND",
            "conditions": [],
            "ip_ranges": [],
        }
        defaults.update(kw)
        return w.Policy(**defaults)

    def test_simple_equals_policy(self):
        p = self._policy(conditions=[{"type": "VendorClass", "operator": "Equals", "value": "Cisco"}])
        cls, warnings = w.policy_to_class(p, "ctx")
        assert warnings == []
        assert cls == {"name": "p", "test": "option[60].hex == 'Cisco'"}

    def test_or_combinator(self):
        p = self._policy(
            condition="OR",
            conditions=[
                {"type": "VendorClass", "operator": "Equals", "value": "Cisco"},
                {"type": "UserClass", "operator": "Equals", "value": "voip"},
            ],
        )
        cls, _ = w.policy_to_class(p, "ctx")
        assert " or " in cls["test"]

    def test_and_combinator(self):
        p = self._policy(
            condition="AND",
            conditions=[
                {"type": "VendorClass", "operator": "Equals", "value": "Cisco"},
                {"type": "UserClass", "operator": "Equals", "value": "voip"},
            ],
        )
        cls, _ = w.policy_to_class(p, "ctx")
        assert " and " in cls["test"]

    def test_not_equals_single_condition_negates(self):
        p = self._policy(conditions=[{"type": "UserClass", "operator": "NotEquals", "value": "trusted"}])
        cls, warnings = w.policy_to_class(p, "ctx")
        assert warnings == []
        assert cls["test"] == "not (option[77].hex == 'trusted')"

    def test_not_equals_multi_condition_is_refused(self):
        p = self._policy(
            conditions=[
                {"type": "UserClass", "operator": "NotEquals", "value": "trusted"},
                {"type": "VendorClass", "operator": "Equals", "value": "Cisco"},
            ]
        )
        cls, warnings = w.policy_to_class(p, "ctx")
        assert cls is None
        assert any("NotEquals" in msg for msg in warnings)

    def test_mixed_equals_and_notequals_is_refused(self):
        p = self._policy(
            conditions=[
                {"type": "UserClass", "operator": "NotEquals", "value": "trusted"},
                {"type": "VendorClass", "operator": "NotEquals", "value": "Cisco"},
            ]
        )
        # both NotEquals (2 conditions) -> refused by the single-condition rule
        cls, warnings = w.policy_to_class(p, "ctx")
        assert cls is None

    def test_disabled_policy_is_skipped(self):
        p = self._policy(enabled=False, conditions=[{"type": "VendorClass", "value": "Cisco"}])
        cls, warnings = w.policy_to_class(p, "ctx")
        assert cls is None
        assert any("disabled" in msg for msg in warnings)

    def test_no_conditions_is_skipped(self):
        p = self._policy(conditions=[])
        cls, warnings = w.policy_to_class(p, "ctx")
        assert cls is None

    def test_unsupported_condition_skips_whole_policy(self):
        p = self._policy(conditions=[{"type": "Subnet", "value": "x"}])
        cls, warnings = w.policy_to_class(p, "ctx")
        assert cls is None
        assert any("not supported" in msg for msg in warnings)

    def test_name_with_spaces_is_sanitized(self):
        p = self._policy(name="VoIP Phones", conditions=[{"type": "VendorClass", "value": "Cisco"}])
        cls, warnings = w.policy_to_class(p, "ctx")
        assert cls["name"] == "VoIP_Phones"
        assert any("sanitized" in msg for msg in warnings)

    def test_policy_options_become_class_option_data(self):
        p = self._policy(
            conditions=[{"type": "VendorClass", "value": "Cisco"}],
            ip_ranges=[],
        )
        p.options = {66: "tftp.example.com"}
        cls, _ = w.policy_to_class(p, "ctx")
        assert cls["option-data"] == [
            {"name": "tftp-server-name", "code": 66, "space": "dhcp4", "csv-format": True, "data": "tftp.example.com"}
        ]


# ── options mapping ──────────────────────────────────────────────────────────


class TestOptionsToKea:
    def test_known_option_maps_through_the_catalog(self):
        entries, warnings = w._options_to_kea({3: "10.0.0.1"}, "ctx")
        assert warnings == []
        assert entries == [{"name": "routers", "code": 3, "space": "dhcp4", "csv-format": True, "data": "10.0.0.1"}]

    def test_unknown_code_is_skipped_with_a_warning(self):
        entries, warnings = w._options_to_kea({250: "whatever"}, "ctx")
        assert entries == []
        assert any("250" in msg and "catalog" in msg for msg in warnings)

    def test_249_converts_to_121_with_a_warning(self):
        entries, warnings = w._options_to_kea({249: "18c0a80a0a000001"}, "ctx")
        assert entries[0]["code"] == 121
        assert entries[0]["data"] == "192.168.10.0/24 - 10.0.0.1"
        assert any("249" in msg for msg in warnings)

    def test_249_ignored_when_121_also_present(self):
        entries, warnings = w._options_to_kea({121: "18c0a80a0a000001", 249: "ff"}, "ctx")
        assert len(entries) == 1 and entries[0]["code"] == 121
        assert any("249" in msg and "ignored" in msg for msg in warnings)

    def test_invalid_value_is_skipped_with_a_warning(self):
        entries, warnings = w._options_to_kea({3: "not-an-ip"}, "ctx")
        assert entries == []
        assert warnings


# ── reservations ─────────────────────────────────────────────────────────────


class TestParseReservationsViaScope:
    def test_mac_normalization_and_type_dhcp_only(self):
        data = _read("windows-dhcp-export.xml")
        plan = w.parse_export(data)
        lan = next(s for s in plan.scopes if s.name == "LAN")
        assert lan.reservations == [("00:11:22:33:44:55", "10.0.1.5", "printer.lan")]

    def test_non_mac_client_id_is_warned_and_skipped(self):
        data = _read("windows-dhcp-export.xml")
        plan = w.parse_export(data)
        lan = next(s for s in plan.scopes if s.name == "LAN")
        assert any("not-a-mac-address" in msg for msg in plan.warnings) or any(
            "non-MAC" in msg for msg in plan.warnings
        )
        assert len(lan.reservations) == 1

    def test_type_both_is_skipped(self):
        data = _read("windows-dhcp-export.xml")
        plan = w.parse_export(data)
        lan = next(s for s in plan.scopes if s.name == "LAN")
        ips = [ip for _mac, ip, _name in lan.reservations]
        assert "10.0.1.6" not in ips  # the Type="Both" reservation


# ── full parser on the fixture(s) ────────────────────────────────────────────


class TestParseExportFixture:
    @pytest.mark.parametrize("filename", ["windows-dhcp-export.xml", "windows-dhcp-export-no-ns.xml"])
    def test_parses_namespaced_and_stripped_copies_identically(self, filename):
        plan = w.parse_export(_read(filename))
        assert [s.name for s in plan.scopes] == ["LAN", "Guest WiFi", "Solo Subnet"]
        assert plan.server_options == {42: "10.0.0.53"}
        assert plan.superscopes == {"HQ": ["10.0.1.0", "10.0.2.0"]}
        assert plan.classes == [{"name": "MSFT 5.0", "type": "Vendor"}]

    def test_inactive_scope_is_flagged(self):
        plan = w.parse_export(_read("windows-dhcp-export.xml"))
        guest = next(s for s in plan.scopes if s.name == "Guest WiFi")
        assert guest.state == "Inactive"
        assert any("Inactive" in msg for msg in plan.warnings)

    def test_billion_laughs_is_refused_not_silently_empty(self):
        with pytest.raises(defusedxml.common.EntitiesForbidden):
            w.parse_export(_read("billion-laughs.xml"))


# ── to_kea, end to end against the fixture ──────────────────────────────────


class TestToKea:
    SUBNET_NAMES = {
        "10.0.1.0": {"id": 10, "name": "LAN"},
        "10.0.2.0": {"id": 11, "name": "Guest WiFi"},
        "10.0.3.0": {"id": 12, "name": "Solo Subnet"},
    }
    ALL_SELECTED = {
        "scopes": {"10.0.1.0": True, "10.0.2.0": True, "10.0.3.0": True},
        "server_options": True,
    }

    def _plan(self):
        return w.parse_export(_read("windows-dhcp-export.xml"))

    def test_default_selection_only_includes_active_scopes(self):
        plan = self._plan()
        cfg, _res, declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, {"scopes": {}})
        assert 11 not in declared  # Guest WiFi is Inactive, not selected by default
        assert 10 in declared and 12 in declared

    def test_server_options_only_imported_when_selected(self):
        plan = self._plan()
        cfg, _res, _declared, _report = w.to_kea(
            plan, None, self.SUBNET_NAMES, {"scopes": {"10.0.3.0": True}, "server_options": False}
        )
        assert "option-data" not in cfg["Dhcp4"] or cfg["Dhcp4"]["option-data"] == []

    def test_superscope_becomes_a_shared_network_when_two_members_included(self):
        plan = self._plan()
        cfg, _res, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, self.ALL_SELECTED)
        nets = cfg["Dhcp4"]["shared-networks"]
        assert len(nets) == 1 and nets[0]["name"] == "HQ"
        ids_in_network = {s["id"] for s in nets[0]["subnet4"]}
        assert ids_in_network == {10, 11}

    def test_lone_superscope_member_does_not_get_a_shared_network(self):
        plan = self._plan()
        selections = {"scopes": {"10.0.1.0": True, "10.0.3.0": True}, "server_options": False}
        cfg, _res, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, selections)
        assert "shared-networks" not in cfg["Dhcp4"] or cfg["Dhcp4"]["shared-networks"] == []
        top_ids = {s["id"] for s in cfg["Dhcp4"].get("subnet4", [])}
        assert 10 in top_ids  # only 1 of HQ's 2 scopes selected -> no shared network

    def test_solo_subnet_is_top_level(self):
        plan = self._plan()
        cfg, _res, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, self.ALL_SELECTED)
        top_ids = {s["id"] for s in cfg["Dhcp4"].get("subnet4", [])}
        assert top_ids == {12}

    def test_reservations_carry_the_right_subnet_id(self):
        plan = self._plan()
        cfg, reservations, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, self.ALL_SELECTED)
        assert reservations == [
            {"subnet-id": 10, "hw-address": "00:11:22:33:44:55", "ip-address": "10.0.1.5", "hostname": "printer.lan"}
        ]

    def test_classless_route_121_lands_on_the_lan_subnet(self):
        plan = self._plan()
        cfg, _res, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, self.ALL_SELECTED)
        lan = next(s for net in cfg["Dhcp4"]["shared-networks"] for s in net["subnet4"] if s["id"] == 10)
        codes = {o["code"] for o in lan["option-data"]}
        assert 121 in codes

    def test_policy_with_ip_range_gets_a_dedicated_guarded_pool(self):
        plan = self._plan()
        cfg, _res, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, self.ALL_SELECTED)
        lan = next(s for net in cfg["Dhcp4"]["shared-networks"] for s in net["subnet4"] if s["id"] == 10)
        voip_pool = next(p for p in lan["pools"] if p["pool"] == "10.0.1.200 - 10.0.1.219")
        assert voip_pool.get("client-class") == "VoIP_Phones"

    def test_policy_without_ip_ranges_guards_the_whole_subnet(self):
        plan = self._plan()
        cfg, _res, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, self.ALL_SELECTED)
        lan = next(s for net in cfg["Dhcp4"]["shared-networks"] for s in net["subnet4"] if s["id"] == 10)
        assert lan.get("client-class") == "Guest_Devices"

    def test_disabled_policy_never_becomes_a_class(self):
        plan = self._plan()
        cfg, _res, _declared, _report = w.to_kea(plan, None, self.SUBNET_NAMES, self.ALL_SELECTED)
        names = {c["name"] for c in cfg["Dhcp4"]["client-classes"]}
        assert "Disabled_Legacy_Rule" not in names

    def test_existing_cidr_is_skipped_with_a_warning(self):
        plan = self._plan()
        existing = {"Dhcp4": {"subnet4": [{"id": 99, "subnet": "10.0.3.0/24", "pools": []}]}}
        cfg, _res, declared, report = w.to_kea(plan, existing, self.SUBNET_NAMES, self.ALL_SELECTED)
        assert 12 not in declared
        assert any("already exists" in msg for msg in report)

    def test_does_not_mutate_the_existing_config(self):
        import copy

        plan = self._plan()
        existing = {"Dhcp4": {"subnet4": []}}
        snapshot = copy.deepcopy(existing)
        w.to_kea(plan, existing, self.SUBNET_NAMES, self.ALL_SELECTED)
        assert existing == snapshot

    def test_scope_with_no_chosen_subnet_id_is_skipped(self):
        plan = self._plan()
        names = dict(self.SUBNET_NAMES)
        del names["10.0.3.0"]
        cfg, _res, declared, report = w.to_kea(plan, None, names, self.ALL_SELECTED)
        assert 12 not in declared
        assert any("no subnet id chosen" in msg for msg in report)
