"""
jen/services/icons.py
──────────────────────
v5.50.0 (Q57) — the Lucide icon set as an inline SVG sprite.

`templates/_icon_sprite.html` (generated by tools/build_icon_sprite.py, included
once in base.html) holds one `<symbol id="i-<name>">` per icon; `icon()` emits
the `<svg><use href="#i-<name>"/></svg>` that references it. Registered as the
Jinja global `icon` (create_app), so every template — including HTMX partials
rendered on their own — can call `{{ icon("pencil") }}` without importing
anything. Icons take their colour from `currentColor`, so they follow the
theme; nothing is baked in.

Unknown names render nothing and log once (tests/test_icons.py fails on any
name used in a template that is not in the sprite, so that never ships).
"""

import logging
import os
import re
from functools import lru_cache

from markupsafe import Markup, escape

logger = logging.getLogger(__name__)

_SPRITE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "templates", "_icon_sprite.html"
)
_warned: set[str] = set()


@lru_cache(maxsize=1)
def icon_names() -> frozenset[str]:
    """Every symbol name in the committed sprite."""
    try:
        with open(_SPRITE, encoding="utf-8") as f:
            return frozenset(re.findall(r'<symbol id="i-([a-z0-9-]+)"', f.read()))
    except OSError:
        return frozenset()


def is_icon(name) -> bool:
    return isinstance(name, str) and name in icon_names()


FALLBACK_NAV_ICON = "puzzle"
_NAME_SHAPED = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def checked_nav_icon(value, owner: str = "") -> str:
    """The icon a plugin manifest's nav entry will actually show (v5.65.3, Q92).

    A value shaped like a sprite name (`cable`, `search-check`) that is NOT in the sprite
    used to fall through `nav_icon` to the literal text, so the Network strip read "cable
    Switch Ports". It is now logged and replaced by `puzzle`. Anything that cannot be a sprite
    name - a plugin's own emoji - is left alone, as `nav_icon` always allowed."""
    if not isinstance(value, str) or not value or is_icon(value) or not _NAME_SHAPED.match(value):
        return value if isinstance(value, str) and value else FALLBACK_NAV_ICON
    logger.warning(f"{owner or 'plugin'}: nav icon {value!r} is not in the icon sprite - showing {FALLBACK_NAV_ICON!r}")
    return FALLBACK_NAV_ICON


def nav_icon(value) -> Markup:
    """A nav/tile icon: a sprite name renders as the icon; anything else (a plugin
    manifest's own emoji) is shown as the plain text it always was."""
    if is_icon(value):
        return icon(value)
    return Markup(escape(value or ""))


def icon(name, cls: str = "", label: str | None = None) -> Markup:
    """`<svg class="ico {cls}" …><use href="#i-{name}"/></svg>`. With `label` the
    icon is announced (`role="img"` + `aria-label`); without, it is decorative
    (`aria-hidden`) — the text next to it carries the meaning."""
    if not is_icon(name):
        if name not in _warned:
            _warned.add(str(name))
            logger.warning(f"icon(): unknown icon name {name!r}")
        return Markup("")
    klass = f"ico {cls}".strip()
    if label:
        a11y = f'role="img" aria-label="{escape(label)}"'
    else:
        a11y = 'aria-hidden="true"'
    return Markup(f'<svg class="{escape(klass)}" {a11y}><use href="#i-{name}"></use></svg>')
