"""
jen/services/win_dhcp_import.py
─────────────────────────────────
v5.24.0 (Q20) — parse a Windows Server `Export-DhcpServer -File x.xml`
export and map it onto Kea's config shape: subnets from scopes, pools
from ranges minus exclusions, options via Q12's catalog, shared
networks from superscopes, and client classes from the subset of
policies Jen can express as a Kea classification expression.

Two pure stages, matching the rest of this codebase's read/mutate
split:
  * `parse_export(data)` — XML bytes -> a `Plan`, a faithful
    representation of what the export actually contains. Never raises
    on a structurally-valid export missing a section it expects
    (records a warning instead); DOES let defusedxml's own exceptions
    propagate for genuinely malicious XML (entity expansion etc.) — the
    route catches those and flashes, rather than this module pretending
    a parse it refused to even attempt "succeeded" with an empty Plan.
  * `to_kea(plan, existing_dhcp4_cfg, subnet_names, selections)` — the
    Plan, filtered by what the review page's checkboxes selected, onto
    a new Dhcp4 config plus the reservation-add rows and `[subnets]`
    entries the route still needs to push separately (reservations live
    in Kea's host DB via the API, not the config file; subnet names are
    Jen's own, not Kea's).

Deliberately NOT verified against a real Windows export — no maintainer
fixture was available (see PENDING.md's Q20 entry, which pins this
exact fallback). `tests/fixtures/windows-dhcp-export.xml` is authored
from Microsoft's own documented `Export-DhcpServer` XML shape, not
generated by a real DC. Treat option-value byte encodings (especially
the RFC 3442 classless-static-route hex) as reasoned-through rather
than confirmed against genuine output.
"""

from __future__ import annotations

import copy
import ipaddress
import re
from dataclasses import dataclass, field

import defusedxml.ElementTree as _ET

from jen.services import auth as _auth
from jen.services import dhcp_options as _opts
from jen.services import kea_classes as _classes
from jen.services import kea_config_edit as _edit
from jen.services import kea_config_view as _view

# ── dataclasses ──────────────────────────────────────────────────────────────


@dataclass
class Policy:
    name: str
    enabled: bool
    processing_order: int
    condition: str  # "AND" | "OR"
    conditions: list[dict] = field(default_factory=list)  # [{"type","operator","value"}]
    ip_ranges: list[tuple[str, str]] = field(default_factory=list)  # [(start, end)]
    options: dict[int, str] = field(default_factory=dict)  # code -> raw joined Value text


@dataclass
class Scope:
    scope_id: str  # Windows' own dotted network address, e.g. "10.0.1.0"
    subnet_mask: str
    name: str
    state: str  # "Active" | "Inactive"
    start_range: str
    end_range: str
    lease_seconds: int
    exclusions: list[tuple[str, str]] = field(default_factory=list)
    options: dict[int, str] = field(default_factory=dict)
    reservations: list[tuple[str, str, str]] = field(default_factory=list)  # (mac, ip, name)
    policies: list[Policy] = field(default_factory=list)
    superscope_name: str | None = None


@dataclass
class Plan:
    server_options: dict[int, str] = field(default_factory=dict)
    scopes: list[Scope] = field(default_factory=list)
    superscopes: dict[str, list[str]] = field(default_factory=dict)  # name -> [scope_id, ...]
    classes: list[dict] = field(default_factory=list)  # raw <Classes> entries — informational only,
    # see the module docstring / admin-guide: Windows "classes" here are
    # vendor/user-class *registrations*, a different concept from Kea's
    # classification classes (which this module derives from policies
    # instead) — nothing in the pinned spec maps them further, so they're
    # surfaced to the review page as a count + names, not applied.
    warnings: list[str] = field(default_factory=list)


# ── XML helpers (namespace-agnostic, attribute-name tolerant) ───────────────


def _local(tag: str) -> str:
    return tag.rsplit("}", 1)[-1] if "}" in tag else tag


def _children(elem, name: str) -> list:
    if elem is None:
        return []
    name = name.lower()
    return [c for c in elem if _local(c.tag).lower() == name]


def _child(elem, name: str):
    found = _children(elem, name)
    return found[0] if found else None


def _attr(elem, name: str, default: str = "") -> str:
    if elem is None:
        return default
    name = name.lower()
    for k, v in elem.attrib.items():
        if _local(k).lower() == name:
            return v
    return default


def _text(elem) -> str:
    return (elem.text or "").strip() if elem is not None else ""


def _bool_attr(elem, name: str, default: bool = True) -> bool:
    v = _attr(elem, name, "").strip().lower()
    if v in ("true", "1", "yes"):
        return True
    if v in ("false", "0", "no"):
        return False
    return default


def _int_attr(elem, name: str, default: int = 0) -> int:
    try:
        return int(_attr(elem, name, str(default)))
    except (TypeError, ValueError):
        return default


# ── lease duration ───────────────────────────────────────────────────────────

_DURATION_RE = re.compile(r"^(?:(\d+)\.)?(\d{1,2}):(\d{2}):(\d{2})$")


def _parse_duration(text: str | None, context: str) -> tuple[int, list[str]]:
    """`d.hh:mm:ss` or `hh:mm:ss` -> total seconds. "Unlimited" or
    absent (and anything else unparsable) -> 86400 with a warning."""
    text = (text or "").strip()
    if not text or text.lower() == "unlimited":
        return 86400, [f"{context}: lease duration unlimited/absent — defaulted to 86400s (1 day)"]
    m = _DURATION_RE.match(text)
    if not m:
        return 86400, [f"{context}: unparsable lease duration {text!r} — defaulted to 86400s (1 day)"]
    days, hh, mm, ss = m.groups()
    total = (int(days) if days else 0) * 86400 + int(hh) * 3600 + int(mm) * 60 + int(ss)
    return total, []


# ── classless-static-route (RFC 3442) decoding ──────────────────────────────


def _decode_classless_routes_hex(hex_text: str, context: str) -> tuple[str, list[str]]:
    """The Windows export stores option 121/249 as a single hex-encoded
    RFC 3442 byte string: repeated {mask_len:1}{dest:ceil(mask_len/8)}
    {router:4} until exhausted. Returns Kea's own csv shape
    ("net/prefix - router, ..." — dhcp_options.py's classless-routes
    type) plus any warnings from a malformed tail."""
    warnings: list[str] = []
    body = re.sub(r"[^0-9a-fA-F]", "", hex_text or "")
    if len(body) % 2:
        warnings.append(f"{context}: classless-static-route hex has an odd digit count — last nibble dropped")
        body = body[:-1]
    try:
        raw = bytes.fromhex(body) if body else b""
    except ValueError:
        return "", [f"{context}: classless-static-route hex could not be decoded"]
    routes = []
    i = 0
    while i < len(raw):
        mask_len = raw[i]
        i += 1
        if mask_len > 32:
            warnings.append(f"{context}: classless-static-route mask length {mask_len} is invalid — stopped decoding")
            break
        needed = (mask_len + 7) // 8
        if i + needed + 4 > len(raw):
            warnings.append(f"{context}: classless-static-route entry is truncated — stopped decoding")
            break
        dest_octets = list(raw[i : i + needed]) + [0] * (4 - needed)
        i += needed
        router_octets = raw[i : i + 4]
        i += 4
        dest = ".".join(str(b) for b in dest_octets)
        router = ".".join(str(b) for b in router_octets)
        routes.append(f"{dest}/{mask_len} - {router}")
    return ", ".join(routes), warnings


# ── option values ────────────────────────────────────────────────────────────


def _parse_option_values(elem, context: str) -> tuple[dict[int, str], list[str]]:
    """<OptionValues><OptionValue OptionId="N"><Value>...</Value>...
    -> {code: raw joined text}. Multiple <Value> children join with
    ", " (Windows' shape for a multi-valued option); 121/249 are
    collapsed to a single <Value> hex string and decoded separately
    below, once the option's actual type is known."""
    out: dict[int, str] = {}
    warnings: list[str] = []
    for ov in _children(elem, "OptionValue"):
        try:
            code = int(_attr(ov, "OptionId"))
        except ValueError:
            warnings.append(f"{context}: OptionValue with a non-numeric OptionId — skipped")
            continue
        values = [_text(v) for v in _children(ov, "Value")]
        out[code] = ", ".join(v for v in values if v)
    return out, warnings


def _options_to_kea(raw_options: dict[int, str], context: str) -> tuple[list[dict], list[str]]:
    """Raw Windows option values -> Kea option-data entries, via Q12's
    catalog. 249 (Microsoft's own classless-static-route code) is
    folded into 121. Unknown codes and values that fail Q12's own
    validate() are skipped with a warning, never written unvalidated."""
    warnings: list[str] = []
    merged: dict[int, str] = {}
    for code, raw in raw_options.items():
        real_code = code
        if code == 249:
            if 121 in raw_options:
                warnings.append(f"{context}: option 249 present alongside 121 — 249 ignored")
                continue
            real_code = 121
            warnings.append(f"{context}: option 249 (Microsoft classless-static-route) converted to standard 121")
        if real_code in merged:
            warnings.append(f"{context}: duplicate option {real_code} — first value kept")
            continue
        merged[real_code] = raw

    entries = []
    for code, raw in merged.items():
        opt_type = _opts.type_for(code)
        if opt_type is None:
            warnings.append(f"{context}: skipped option {code} (not in Jen's catalog)")
            continue
        if opt_type == "classless-routes":
            data, decode_warnings = _decode_classless_routes_hex(raw, context)
            warnings.extend(decode_warnings)
            if not data:
                continue
        else:
            data = raw
        err = _opts.validate(opt_type, data)
        if err:
            warnings.append(f"{context}: skipped option {code} ({_opts.V4_OPTIONS[code]['name']}) — {err}")
            continue
        entries.append(
            {
                "name": _opts.V4_OPTIONS[code]["name"],
                "code": code,
                "space": "dhcp4",
                "csv-format": True,
                "data": _opts.normalize(opt_type, data),
            }
        )
    return entries, warnings


# ── reservations ─────────────────────────────────────────────────────────────

_CLIENT_ID_RE = re.compile(r"^[0-9a-fA-F]{2}([:-][0-9a-fA-F]{2}){5}$")


def _parse_reservations(elem, context: str) -> tuple[list[tuple[str, str, str]], list[str]]:
    out = []
    warnings = []
    for r in _children(elem, "Reservation"):
        rtype = _attr(r, "Type", "Dhcp")
        if rtype.lower() not in ("dhcp",):
            warnings.append(f"{context}: reservation type {rtype!r} not imported (Both/Bootp are out of scope)")
            continue
        ip = _attr(r, "IPAddress")
        client_id = _attr(r, "ClientId")
        name = _attr(r, "Name")
        if not _CLIENT_ID_RE.match(client_id or ""):
            warnings.append(f"{context}: reservation {ip or '?'} has a non-MAC ClientId {client_id!r} — skipped")
            continue
        mac = client_id.replace("-", ":").lower()
        if not _auth.valid_ip(ip):
            warnings.append(f"{context}: reservation for {mac} has an invalid IP {ip!r} — skipped")
            continue
        if name and not _auth.valid_hostname(name):
            warnings.append(f"{context}: reservation {ip} hostname {name!r} failed validation — imported without it")
            name = ""
        out.append((mac, ip, name))
    return out, warnings


# ── policies ─────────────────────────────────────────────────────────────────


def _parse_policies(elem, context: str) -> tuple[list[Policy], list[str]]:
    out = []
    warnings = []
    for p in _children(elem, "Policy"):
        name = _attr(p, "Name")
        conditions = []
        for c in _children(_child(p, "Conditions"), "Condition"):
            conditions.append(
                {
                    "type": _attr(c, "Type"),
                    "operator": _attr(c, "Operator", "Equals"),
                    "value": _attr(c, "Value"),
                }
            )
        ip_ranges = []
        for r in _children(_child(p, "IPRanges"), "IPRange"):
            ip_ranges.append((_attr(r, "StartRange"), _attr(r, "EndRange")))
        options, opt_warnings = _parse_option_values(_child(p, "OptionValues"), f"{context} policy {name}")
        warnings.extend(opt_warnings)
        out.append(
            Policy(
                name=name,
                enabled=_bool_attr(p, "Enabled", True),
                processing_order=_int_attr(p, "ProcessingOrder", 0),
                condition=_attr(p, "Condition", "AND").upper(),
                conditions=conditions,
                ip_ranges=ip_ranges,
                options=options,
            )
        )
    return out, warnings


# ── scopes ───────────────────────────────────────────────────────────────────


def _parse_scope(elem) -> tuple[Scope, list[str]]:
    scope_id = _attr(elem, "ScopeId")
    name = _attr(elem, "Name") or scope_id
    context = f"scope {name} ({scope_id})"
    warnings: list[str] = []

    lease_seconds, dur_warnings = _parse_duration(_attr(elem, "LeaseDuration"), context)
    warnings.extend(dur_warnings)

    exclusions = []
    for r in _children(_child(elem, "ExclusionRanges"), "IPRange"):
        exclusions.append((_attr(r, "StartRange"), _attr(r, "EndRange")))

    reservations, res_warnings = _parse_reservations(_child(elem, "Reservations"), context)
    warnings.extend(res_warnings)

    options, opt_warnings = _parse_option_values(_child(elem, "OptionValues"), context)
    warnings.extend(opt_warnings)

    policies, policy_warnings = _parse_policies(_child(elem, "Policies"), context)
    warnings.extend(policy_warnings)

    scope = Scope(
        scope_id=scope_id,
        subnet_mask=_attr(elem, "SubnetMask"),
        name=name,
        state=_attr(elem, "State", "Active"),
        start_range=_attr(elem, "StartRange"),
        end_range=_attr(elem, "EndRange"),
        lease_seconds=lease_seconds,
        exclusions=exclusions,
        options=options,
        reservations=reservations,
        policies=policies,
        superscope_name=_attr(elem, "SuperscopeName") or None,
    )
    if scope.state.lower() != "active":
        warnings.append(f"{context}: scope is Inactive in Windows — imported, unticked by default")
    return scope, warnings


def _parse_superscopes(elem) -> dict[str, list[str]]:
    out: dict[str, list[str]] = {}
    for sc in _children(elem, "Superscope"):
        name = _attr(sc, "Name")
        ids = [_text(s) for s in _children(sc, "ScopeId") if _text(s)]
        if name:
            out[name] = ids
    return out


def _parse_classes(elem) -> list[dict]:
    out = []
    for c in _children(elem, "Class"):
        out.append({"name": _attr(c, "Name"), "type": _attr(c, "Type")})
    return out


# ── top level ────────────────────────────────────────────────────────────────


def parse_export(data: bytes) -> Plan:
    """`Export-DhcpServer -File x.xml`'s bytes -> a Plan. Raises
    whatever defusedxml raises on genuinely malicious XML (entity
    expansion, external references) — the caller decides how to
    present that; anything else missing or malformed inside an
    otherwise well-formed document is recorded as a warning instead."""
    root = _ET.fromstring(data)
    plan = Plan()

    ipv4 = None
    for child in root:
        if _local(child.tag).lower() == "ipv4":
            ipv4 = child
            break
    if ipv4 is None:
        plan.warnings.append("No <IPv4> section found in the export — nothing to import.")
        return plan

    server_options, opt_warnings = _parse_option_values(_child(ipv4, "OptionValues"), "server")
    plan.server_options = server_options
    plan.warnings.extend(opt_warnings)

    scopes_elem = _child(ipv4, "Scopes")
    for scope_elem in _children(scopes_elem, "Scope"):
        scope, scope_warnings = _parse_scope(scope_elem)
        plan.scopes.append(scope)
        plan.warnings.extend(scope_warnings)

    plan.superscopes = _parse_superscopes(_child(ipv4, "Superscopes"))
    plan.classes = _parse_classes(_child(ipv4, "Classes"))

    if not plan.scopes:
        plan.warnings.append("No scopes found in the export.")

    return plan


# ── pool math ────────────────────────────────────────────────────────────────


def _ip2int(s: str) -> int:
    return int(ipaddress.IPv4Address(s))


def _int2ip(i: int) -> str:
    return str(ipaddress.IPv4Address(i))


def split_pool_by_exclusions(start: str, end: str, exclusions: list[tuple[str, str]]) -> list[tuple[int, int]]:
    """[start, end] minus each exclusion, as a list of (start_int, end_int)
    sub-ranges (integers so the pool-carving below can keep splitting
    without repeated string<->int round trips). An exclusion covering
    the whole range legitimately yields an empty list — a
    reservation-only subnet is valid in Kea (Gotcha in PENDING.md)."""
    segments = [(_ip2int(start), _ip2int(end))]
    for exc_start, exc_end in exclusions:
        if not exc_start or not exc_end:
            continue
        es, ee = _ip2int(exc_start), _ip2int(exc_end)
        new_segments = []
        for seg_s, seg_e in segments:
            if ee < seg_s or es > seg_e:
                new_segments.append((seg_s, seg_e))
                continue
            if es > seg_s:
                new_segments.append((seg_s, es - 1))
            if ee < seg_e:
                new_segments.append((ee + 1, seg_e))
        segments = new_segments
    return [(s, e) for s, e in segments if s <= e]


def _carve_pool(segments: list[tuple[int, int]], want_start: int, want_end: int) -> tuple[list[tuple[int, int]], bool]:
    """Remove [want_start, want_end] from whichever segment fully
    contains it, replacing that one segment with up to two remaining
    pieces. Returns (new_segments, carved_ok) — carved_ok is False (segments
    unchanged) when the requested range doesn't sit entirely inside a
    single existing segment (split across exclusions, outside the pool
    entirely, or overlapping two policies)."""
    for i, (seg_s, seg_e) in enumerate(segments):
        if seg_s <= want_start and want_end <= seg_e:
            out = segments[:i] + segments[i + 1 :]
            if seg_s < want_start:
                out.append((seg_s, want_start - 1))
            if want_end < seg_e:
                out.append((want_end + 1, seg_e))
            return out, True
    return segments, False


# ── policies -> Kea client classes ──────────────────────────────────────────

_WINDOWS_CONDITION_FIELDS = {
    "vendorclass": "vendor_class",
    "userclass": "user_class",
    "clientid": "client_id",
    "relayagentinformation": "circuit_id",
}


def _sanitize_class_name(name: str) -> str:
    sanitized = re.sub(r"[^A-Za-z0-9_-]", "_", name or "")
    if not sanitized or not sanitized[0].isalpha():
        sanitized = "policy_" + sanitized
    return sanitized[:64]


def _condition_to_rule(cond: dict, context: str) -> tuple[dict | None, str | None]:
    """(rule, None) or (None, warning). MACAddress with a trailing `*`
    and a 3-byte prefix maps to mac_oui; a full 6-byte value (wildcard
    or not) maps to mac."""
    ctype = (cond.get("type") or "").strip().lower()
    value = cond.get("value") or ""
    if ctype == "macaddress":
        stripped = value.rstrip("*")
        hex_only = re.sub(r"[:\-]", "", stripped)
        field_name = "mac_oui" if value.endswith("*") and len(hex_only) == 6 else "mac"
        return {"field": field_name, "op": "equals", "value": stripped}, None
    field_name = _WINDOWS_CONDITION_FIELDS.get(ctype)
    if field_name is None:
        return None, f"{context}: condition type {cond.get('type')!r} is not supported"
    return {"field": field_name, "op": "equals", "value": value}, None


def policy_to_class(policy: Policy, context: str) -> tuple[dict | None, list[str]]:
    """A Policy -> a Kea client-class dict ({"name", "test", possibly
    "option-data"}), or None with the warning explaining why it can't
    be expressed. Never raises."""
    warnings: list[str] = []
    label = f"{context} policy {policy.name!r}"
    if not policy.enabled:
        warnings.append(f"{label}: disabled in Windows — not imported")
        return None, warnings
    if not policy.conditions:
        warnings.append(f"{label}: has no conditions — not imported")
        return None, warnings

    operators = {(c.get("operator") or "Equals").strip().lower() for c in policy.conditions}
    negate = False
    if operators == {"notequals"}:
        if len(policy.conditions) > 1:
            warnings.append(f"{label}: NotEquals is only supported on a single-condition policy — not imported")
            return None, warnings
        negate = True
    elif "notequals" in operators:
        warnings.append(f"{label}: mixes Equals and NotEquals conditions — not imported")
        return None, warnings

    rules = []
    for cond in policy.conditions:
        rule, warning = _condition_to_rule(cond, label)
        if warning:
            warnings.append(f"{warning} — policy not imported")
            return None, warnings
        rules.append(rule)

    combinator = "any" if policy.condition == "OR" else "all"
    try:
        expr = _classes.build_expression(rules, combinator=combinator, negate=negate)
    except ValueError as e:
        warnings.append(f"{label}: not imported: {e}")
        return None, warnings

    name = policy.name
    if not _auth.valid_class_name(name):
        sanitized = _sanitize_class_name(name)
        warnings.append(f"{label}: name sanitized to {sanitized!r} for Kea")
        name = sanitized

    class_dict = {"name": name, "test": expr}
    if policy.options:
        option_entries, opt_warnings = _options_to_kea(policy.options, label)
        warnings.extend(opt_warnings)
        if option_entries:
            class_dict["option-data"] = option_entries
    return class_dict, warnings


# ── scope -> subnet4 ─────────────────────────────────────────────────────────


def _prefix_len(mask: str) -> int:
    try:
        octets = [int(o) for o in mask.split(".")]
        bits = "".join(f"{o:08b}" for o in octets)
        return bits.count("1")
    except Exception:
        return 24


@dataclass
class MappedScope:
    """Everything one scope produced, before it's stitched into a real
    Dhcp4 config: the plain subnet4 block (pools carry no metadata of
    their own — `pool_guards` names which exact pool string, matching
    what's literally in `subnet["pools"]`, guards which class), the
    classes it wants added globally, and which of those guard the whole
    subnet vs. one specific pool."""

    subnet: dict
    classes: list[dict] = field(default_factory=list)
    pool_guards: list[tuple[str, str]] = field(default_factory=list)  # (pool string, class name)
    subnet_guards: list[str] = field(default_factory=list)  # class names
    warnings: list[str] = field(default_factory=list)


def scope_to_subnet(scope: Scope, jen_id: int) -> MappedScope:
    """Map one Scope onto a subnet4 block plus whatever classes its
    policies produce. A policy with IPRanges that fit cleanly inside one
    of the scope's own pool segments gets its own carved-out pool,
    guarded by its class; anything else (no IPRanges, or a range that
    doesn't fit a single segment) guards the whole subnet instead, with
    a warning in the latter case."""
    context = f"scope {scope.name}"
    warnings: list[str] = []

    segments = split_pool_by_exclusions(scope.start_range, scope.end_range, scope.exclusions)
    if not segments and scope.exclusions:
        warnings.append(f"{context}: exclusions cover the entire range — no pools (reservation-only subnet)")

    classes: list[dict] = []
    pool_guards: list[tuple[str, str]] = []
    subnet_guards: list[str] = []
    carved_pools: list[tuple[int, int]] = []

    for policy in sorted(scope.policies, key=lambda p: p.processing_order):
        class_dict, class_warnings = policy_to_class(policy, context)
        warnings.extend(class_warnings)
        if class_dict is None:
            continue
        classes.append(class_dict)

        carved = None
        for r_start, r_end in policy.ip_ranges:
            if not r_start or not r_end:
                continue
            want_s, want_e = _ip2int(r_start), _ip2int(r_end)
            segments, ok = _carve_pool(segments, want_s, want_e)
            if ok:
                carved = (want_s, want_e)
                break
            warnings.append(
                f"{context}: policy {policy.name!r}'s IP range {r_start}-{r_end} doesn't sit inside a single "
                f"existing pool — {class_dict['name']} attached to the whole subnet instead"
            )
        if carved is not None:
            carved_pools.append(carved)
            pool_guards.append((f"{_int2ip(carved[0])} - {_int2ip(carved[1])}", class_dict["name"]))
        else:
            subnet_guards.append(class_dict["name"])

    pools = [{"pool": f"{_int2ip(s)} - {_int2ip(e)}"} for s, e in segments + carved_pools]

    option_entries, opt_warnings = _options_to_kea(scope.options, context)
    warnings.extend(opt_warnings)

    subnet = {
        "id": jen_id,
        "subnet": f"{scope.scope_id}/{_prefix_len(scope.subnet_mask)}",
        "pools": pools,
        "valid-lifetime": scope.lease_seconds,
        "option-data": option_entries,
    }
    return MappedScope(
        subnet=subnet, classes=classes, pool_guards=pool_guards, subnet_guards=subnet_guards, warnings=warnings
    )


# ── top-level mapping ────────────────────────────────────────────────────────


def to_kea(plan: Plan, existing_dhcp4_cfg: dict | None, subnet_names: dict, selections: dict):
    """The Plan, filtered by the review page's choices, onto a new
    Dhcp4 config. Returns (new_cfg, reservations, subnets_to_declare, report):
      * new_cfg — existing_dhcp4_cfg with the selected scopes' subnets
        (nested under a shared network when their Windows superscope has
        at least one other included member), classes, and guard
        attachments added. Never mutates the caller's dict.
      * reservations — [{"subnet-id","hw-address","ip-address","hostname"}, ...]
        ready for a reservation-add loop — these live in Kea's host DB,
        not the config file, so the route pushes them separately.
      * subnets_to_declare — {jen_id: {"name","cidr"}} for
        app_config.write_subnets_config() — merge with the EXISTING
        SUBNET_MAP yourself; this only carries the new entries.
      * report — every warning, in the order encountered, plus one
        summary line per imported scope.

    `subnet_names` is {scope_id: {"id": <jen subnet id>, "name": <friendly name>}}
    for every scope the caller wants considered (whether or not it ends
    up actually included — `selections["scopes"]` decides that).
    `selections` is {"scopes": {scope_id: bool}, "server_options": bool}.
    """
    cfg = copy.deepcopy(existing_dhcp4_cfg) if existing_dhcp4_cfg else {}
    cfg.setdefault("Dhcp4", {})
    report: list[str] = list(plan.warnings)
    reservations: list[dict] = []
    subnets_to_declare: dict[int, dict] = {}

    existing_cidrs = {s.get("subnet") for s, _sn in _view.iter_subnet4(cfg["Dhcp4"])}

    scope_selections = selections.get("scopes", {})
    included_scopes = [s for s in plan.scopes if scope_selections.get(s.scope_id, s.state.lower() == "active")]

    if selections.get("server_options") and plan.server_options:
        entries, warnings = _options_to_kea(plan.server_options, "server")
        report.extend(warnings)
        existing = cfg["Dhcp4"].setdefault("option-data", [])
        existing_codes = {e.get("code") for e in existing if isinstance(e, dict)}
        for e in entries:
            if e["code"] in existing_codes:
                report.append(f"server option {e['code']} already present at global level — kept as-is")
                continue
            existing.append(e)

    # Which scope_ids share a superscope with at least one OTHER included
    # scope — a superscope containing only one included member isn't
    # worth a shared network (nothing shares it with).
    network_for_scope: dict[str, str] = {}
    included_ids = {s.scope_id for s in included_scopes}
    for net_name, member_ids in plan.superscopes.items():
        included_members = [sid for sid in member_ids if sid in included_ids]
        if len(included_members) >= 2:
            for sid in included_members:
                network_for_scope[sid] = net_name

    for net_name in sorted(set(network_for_scope.values())):
        cfg, code = _edit.create_shared_network4(cfg, net_name)
        if code == "exists":
            report.append(f"shared network {net_name!r} already exists in Kea — reusing it")

    for scope in included_scopes:
        names = subnet_names.get(scope.scope_id) or {}
        jen_id = names.get("id")
        friendly_name = names.get("name") or scope.name
        if jen_id is None:
            report.append(f"scope {scope.name}: no subnet id chosen — skipped")
            continue

        mapped = scope_to_subnet(scope, jen_id)
        report.extend(mapped.warnings)

        if mapped.subnet["subnet"] in existing_cidrs:
            report.append(f"scope {scope.name}: CIDR {mapped.subnet['subnet']} already exists in Kea — skipped")
            continue
        existing_cidrs.add(mapped.subnet["subnet"])

        cfg, code = _edit.add_subnet4(cfg, mapped.subnet, shared_network=network_for_scope.get(scope.scope_id))
        if code != "ok":
            report.append(f"scope {scope.name}: could not add subnet {jen_id} ({code}) — skipped")
            continue

        for class_dict in mapped.classes:
            cfg, _code = _edit.upsert_class4(cfg, class_dict)

        for class_name in mapped.subnet_guards:
            cfg, code = _edit.attach_class4(cfg, class_name, "subnet", jen_id, mode="guard")
            if code != "ok":
                report.append(f"scope {scope.name}: could not attach class {class_name!r} to the subnet ({code})")

        for pool_str, class_name in mapped.pool_guards:
            cfg, code = _edit.attach_class4(cfg, class_name, "pool", (jen_id, pool_str), mode="guard")
            if code != "ok":
                report.append(f"scope {scope.name}: could not attach class {class_name!r} to its pool ({code})")

        subnets_to_declare[jen_id] = {"name": friendly_name, "cidr": mapped.subnet["subnet"]}

        for mac, ip, hostname in scope.reservations:
            reservations.append({"subnet-id": jen_id, "hw-address": mac, "ip-address": ip, "hostname": hostname})

        report.append(
            f"scope {scope.name}: mapped to subnet {jen_id} ({mapped.subnet['subnet']}), "
            f"{len(mapped.subnet['pools'])} pool(s), {len(mapped.classes)} class(es), "
            f"{len(scope.reservations)} reservation(s)"
        )

    return cfg, reservations, subnets_to_declare, report
