#!/usr/bin/env python3
"""
tools/build_icon_sprite.py — turn static/icons/src/*.svg (Lucide sources, ISC
licence, see static/icons/LICENSE) into templates/_icon_sprite.html: ONE hidden
inline <svg> holding a <symbol id="i-<name>" viewBox="0 0 24 24"> per icon.
base.html includes it once right after <body>; pages reference an icon with
<use href="#i-<name>"/> (see jen/services/icons.py). Inline + same-document
means no fetch and no CSP change.

    py tools/build_icon_sprite.py            # rewrite templates/_icon_sprite.html
    py tools/build_icon_sprite.py --check    # exit 1 if it would change

tests/test_icons.py builds the sprite into a temp file and asserts it equals
the committed one (drift guard). Stdlib only.
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "static" / "icons" / "src"
OUT = ROOT / "templates" / "_icon_sprite.html"

_INNER = re.compile(r"<svg\b[^>]*>(.*?)</svg>", re.S)


def build(src_dir: pathlib.Path = SRC) -> str:
    symbols = []
    for path in sorted(src_dir.glob("*.svg")):
        m = _INNER.search(path.read_text(encoding="utf-8"))
        if not m:
            raise SystemExit(f"{path.name}: no <svg> body found")
        inner = re.sub(r"\s+", " ", m.group(1)).strip()
        inner = re.sub(r"\s*/>", "/>", inner).replace("> <", "><")
        symbols.append(f'<symbol id="i-{path.stem}" viewBox="0 0 24 24">{inner}</symbol>')
    return (
        "{#- GENERATED by tools/build_icon_sprite.py from static/icons/src/*.svg (Lucide, ISC). Do not edit. -#}\n"
        '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true" focusable="false">\n'
        + "\n".join(symbols)
        + "\n</svg>\n"
    )


def main(argv: list[str]) -> int:
    text = build()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.replace("\r\n", "\n") != text:
            print("templates/_icon_sprite.html is out of date — run: py tools/build_icon_sprite.py")
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({text.count('<symbol')} icons)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
