#!/usr/bin/env python3
"""Turn a markdown page's runnable command blocks into one bash script (v5.67.0-beta.10, Q122).

docs/manual-install.md used to be prose nobody ran: it told an operator to copy a `jen.service` that had
stopped shipping, and to append an `Environment=` line to the file that was not there. The page is now
executable. Two kinds of marker, each an HTML comment on its own line:

    <!-- ci:run -->          the NEXT fenced ```bash block is part of the script, verbatim
    <!-- ci:hook NAME -->    a call `ci_hook NAME` is emitted here — where the page tells a human to do
                             something a script cannot (edit a file, paste SQL); the CI job defines the
                             function (.github/scripts/manual-install-hooks.sh) and does that thing

A bash block with no marker is documentation only and is never run. A marker that does not meet what it
promises (a `ci:run` with no fence after it, an unterminated fence, a fence that is not bash, a malformed
hook name) is an error, not a silently-skipped block — the failure mode this tool exists to close is a
page and its test drifting apart without anyone noticing.

    python3 tools/doc_commands.py docs/manual-install.md > run.sh

`--hooks` prints the hook names the page uses, one per line (the test compares them to the CI job's).
Pure stdlib.
"""

import re
import sys

RUN_RE = re.compile(r"^\s*<!--\s*ci:run\s*-->\s*$")
HOOK_RE = re.compile(r"^\s*<!--\s*ci:hook\s+([a-z][a-z0-9-]*)\s*-->\s*$")
ANY_MARKER_RE = re.compile(r"<!--\s*ci:")
FENCE_RE = re.compile(r"^```(\w*)\s*$")


class DocError(ValueError):
    pass


def extract(text: str) -> list[tuple[str, str, int]]:
    """[("run", body, line) | ("hook", name, line)] in page order."""
    lines = text.replace("\r\n", "\n").split("\n")
    out: list[tuple[str, str, int]] = []
    i = 0
    pending_run = None  # line number of a ci:run waiting for its fence
    while i < len(lines):
        line = lines[i]
        n = i + 1
        if RUN_RE.match(line):
            if pending_run is not None:
                raise DocError(f"line {pending_run}: ci:run with no fenced block before the next marker (line {n})")
            pending_run = n
            i += 1
            continue
        m = HOOK_RE.match(line)
        if m:
            if pending_run is not None:
                raise DocError(f"line {pending_run}: ci:run with no fenced block before the hook on line {n}")
            out.append(("hook", m.group(1), n))
            i += 1
            continue
        if ANY_MARKER_RE.search(line):
            raise DocError(f"line {n}: malformed ci: marker: {line.strip()!r}")
        f = FENCE_RE.match(line)
        if f:
            lang = f.group(1)
            j = i + 1
            body = []
            while j < len(lines) and not FENCE_RE.match(lines[j]) and lines[j].rstrip() != "```":
                body.append(lines[j])
                j += 1
            if j >= len(lines):
                raise DocError(f"line {n}: fenced block is never closed")
            if pending_run is not None:
                if lang != "bash":
                    raise DocError(
                        f"line {pending_run}: ci:run is followed by a ```{lang or '(no language)'} block, not bash"
                    )
                out.append(("run", "\n".join(body), n))
                pending_run = None
            i = j + 1
            continue
        if pending_run is not None and line.strip():
            raise DocError(
                f"line {pending_run}: ci:run must be followed directly by a fenced block (line {n} is prose)"
            )
        i += 1
    if pending_run is not None:
        raise DocError(f"line {pending_run}: ci:run at the end of the page with no block after it")
    return out


def render(items: list[tuple[str, str, int]]) -> str:
    parts = ["# generated by tools/doc_commands.py — do not edit", ""]
    for kind, body, line in items:
        if kind == "hook":
            parts.append(f"# --- hook {body} (page line {line})")
            parts.append(f"ci_hook {body}")
        else:
            parts.append(f"# --- block at page line {line}")
            parts.append(body)
        parts.append("")
    return "\n".join(parts)


def main(argv: list[str]) -> int:
    hooks_only = "--hooks" in argv
    paths = [a for a in argv if not a.startswith("--")]
    if len(paths) != 1:
        print("usage: doc_commands.py [--hooks] PAGE.md", file=sys.stderr)
        return 2
    with open(paths[0], encoding="utf-8") as f:
        text = f.read()
    try:
        items = extract(text)
    except DocError as e:
        print(f"{paths[0]}: {e}", file=sys.stderr)
        return 1
    if hooks_only:
        for kind, body, _line in items:
            if kind == "hook":
                print(body)
        return 0
    sys.stdout.write(render(items))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
