#!/usr/bin/env python3
"""
tools/extract_inline_styles.py — v5.53.0 (Q60): move static inline `style="…"`
attributes out of the templates and into classes.

    py tools/extract_inline_styles.py templates/dashboard.html templates/ddns.html
    py tools/extract_inline_styles.py --all          # every template that extends base.html
    py tools/extract_inline_styles.py --check        # regenerate the CSS only, touch no template
    py tools/extract_inline_styles.py --all --dry    # count what would change

For each `style="decls"` whose value is static (no Jinja) and appears at least twice across
the templates, the tool picks a class `u-<6 hex of sha1(normalised decls)>`, records it in
tools/inline_style_map.json (append-only: a class name never changes), rewrites the tag
(adding the class to an existing `class="…"` or creating one) and regenerates
static/css/ui-classes.css from the map. Each rule doubles its selector (`.u-x.u-x`) so it
keeps the precedence the inline style had over ordinary one-class rules; a script-set inline
style still wins.

Left alone on purpose: any style containing Jinja; `display:none` (scripts read and set
`style.display` on those); `position:fixed` (modals and overlays that scripts toggle);
one-offs; and templates that do not extend base.html (login, MFA challenge, forced password
change, error pages), which do not load the stylesheet.

A fixed multi-column `grid-template-columns` also gets a phone rule that collapses it to one
column (a form laid out in columns on a desktop is one column on a phone).
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "templates"
MAP_FILE = ROOT / "tools" / "inline_style_map.json"
CSS_FILE = ROOT / "static" / "css" / "ui-classes.css"

MIN_USES = 2  # a declaration used once stays inline; a class per one-off would only bloat the stylesheet
SKIP_PROPS = re.compile(r"display\s*:\s*none|position\s*:\s*fixed")
STYLE_RE = re.compile(r'style="([^"]*)"')
CLASS_RE = re.compile(r'(\s)class="([^"]*)"')
FIXED_GRID = re.compile(r"grid-template-columns\s*:\s*([^;]+)")
EXTENDS_RE = re.compile(r"{%\s*extends\s+[\"']base.html[\"']")


def read(path) -> str:
    with open(path, encoding="utf-8", newline="") as f:
        return f.read()


def write(path, text: str) -> None:
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(text)


def normalise(value: str) -> str:
    v = re.sub(r"\s+", " ", value.strip())
    v = re.sub(r"\s*([:;])\s*", r"\1", v)
    return v.rstrip(";")


def class_for(decl: str) -> str:
    return "u-" + hashlib.sha1(decl.encode("utf-8")).hexdigest()[:6]


def stacks_on_phone(decl: str) -> bool:
    m = FIXED_GRID.search(decl)
    if not m:
        return False
    cols = m.group(1)
    if "auto-fit" in cols or "auto-fill" in cols:
        return False
    return len(cols.split()) > 1 or bool(re.search(r"repeat\(\s*\d+", cols))


def static_decl(value: str) -> str | None:
    if not value.strip() or "{" in value or SKIP_PROPS.search(value):
        return None
    return normalise(value)


def count_uses() -> dict[str, int]:
    """How often each static declaration set appears across every template."""
    uses: dict[str, int] = {}
    for p in TEMPLATES.glob("*.html"):
        for m in STYLE_RE.finditer(read(p)):
            d = static_decl(m.group(1))
            if d:
                uses[d] = uses.get(d, 0) + 1
    return uses


def load_map() -> dict[str, str]:
    if MAP_FILE.exists():
        return json.loads(read(MAP_FILE))
    return {}


def render_css(mapping: dict[str, str]) -> str:
    out = [
        "/* GENERATED by tools/extract_inline_styles.py from tools/inline_style_map.json — do not edit.",
        "   v5.53.0 (Q60): the static inline styles that used to sit on individual elements. Each rule",
        "   doubles its selector so it keeps the precedence the inline style had over one-class rules.",
        "   New markup should use the tokens and utilities in base.html (docs/ui.md), not add classes here. */",
    ]
    ordered = sorted(mapping.items(), key=lambda kv: kv[1])
    for decl, cls in ordered:
        out.append(f".{cls}.{cls}{{{decl}}}")
    phone = [c for d, c in ordered if stacks_on_phone(d)]
    if phone:
        out.append("@media (max-width:768px){")
        for cls in phone:
            out.append(f".{cls}.{cls}{{grid-template-columns:1fr}}")
        out.append("}")
    return "\n".join(out) + "\n"


def convert(text: str, mapping: dict[str, str], uses: dict[str, int]) -> tuple[str, int]:
    changed = 0
    for m in reversed(list(STYLE_RE.finditer(text))):
        decl = static_decl(m.group(1))
        if decl is None or (uses.get(decl, 0) < MIN_USES and decl not in mapping):
            continue
        start = text.rfind("<", 0, m.start())
        if start < 0 or not text[start + 1 : start + 2].isalpha() or ">" in text[start : m.start()]:
            continue
        end = text.find(">", m.end())
        if end < 0 or "<" in text[m.end() : end]:
            continue
        tag = text[start : end + 1]
        before, after = tag[: m.start() - start], tag[m.end() - start :]
        # the tag with the style attribute (and the space before it) removed
        joined = before.rstrip(" ") + after if after.startswith((">", "/")) else before + after
        cm = CLASS_RE.search(joined)
        cls = mapping.setdefault(decl, class_for(decl))
        if cm:
            nxt = joined[cm.end() : cm.end() + 1]
            if nxt not in ("", " ", "\n", "\t", ">", "/"):
                continue  # a class attribute with quotes inside Jinja: leave the tag alone
            new_tag = joined[: cm.start()] + f'{cm.group(1)}class="{cm.group(2)} {cls}"' + joined[cm.end() :]
        else:
            new_tag = before + f'class="{cls}"' + after
        text = text[:start] + new_tag + text[end + 1 :]
        changed += 1
    return text, changed


def main(argv: list[str]) -> int:
    dry = "--dry" in argv
    check = "--check" in argv
    files = [a for a in argv if not a.startswith("--")]
    if "--all" in argv:
        files = [str(p) for p in sorted(TEMPLATES.glob("*.html"))]
    mapping = load_map()
    uses = count_uses()
    total = 0
    if not check:
        for f in files:
            p = pathlib.Path(f)
            if not p.is_absolute():
                p = ROOT / p
            if not p.exists():
                print("missing", f)
                continue
            raw = read(p)
            if not (p.name.startswith("_") or EXTENDS_RE.search(raw)):
                print(f"skip (does not extend base.html): {p.name}")
                continue
            crlf = "\r\n" in raw
            new, n = convert(raw.replace("\r\n", "\n"), mapping, uses)
            total += n
            print(f"{p.name}: {n}")
            if n and not dry:
                write(p, new.replace("\n", "\r\n") if crlf else new)
    if not dry:
        write(MAP_FILE, json.dumps(dict(sorted(mapping.items())), indent=1, ensure_ascii=False) + "\n")
        CSS_FILE.parent.mkdir(parents=True, exist_ok=True)
        write(CSS_FILE, render_css(mapping))
    seen: dict[str, str] = {}
    for d, c in mapping.items():
        assert seen.setdefault(c, d) == d, f"class collision {c}"
    print(f"converted {total}; {len(mapping)} classes")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
