name: CI

on:
  push:
    branches: ['**']
  pull_request:

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/tests.yml
    secrets:
      JEN_DOCS_FORBIDDEN: ${{ secrets.JEN_DOCS_FORBIDDEN }}
